import { Inter } from 'next/font/google';
import '../styles/globals.css';
import '../styles/vendors/menu.css';
import 'swiper/css';
import 'swiper/css/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
