import localFont from 'next/font/local';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import '@/styles/vendors/menu.css';
import 'swiper/css';
import 'swiper/css/navigation';

const myFont = localFont({
  src: './DMSans-Bold.woff2',
  variable: '--font-DMSans',
});
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${(inter.variable, inter.variable)}`}>{children}</body>
    </html>
  );
}
